# Conda is only used during local development of bignbit
# The Cumulus module runtime uses a lambda container image based on the official GDAL docker image. See docker/Dockerfile
name: bignbit
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - gdal=3.6.3
